name: __CONTAINER_GROUP__
services:
  __CONTAINER_NAME__:
    image: __CONTAINER_IMAGE__:__CONTAINER_TAG__
    container_name: __CONTAINER_NAME__
    ports:
      - __HOST_PORT__:__CONTAINER_PORT__
    restart: __CONTAINER_RESTART__
    environment:
__ENV_LIST__
__VOL_LIST__